services:
  app:
    build:
      context: .
      dockerfile: Esteira/Dockerfile
    image: puredo/esteira-back-api:1.0
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/banco_da_esteira
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URI: ${SPOTIFY_REDIRECT_URI}
      SPOTIFY_RESPONSE_TYPE: ${SPOTIFY_RESPONSE_TYPE}
      SPOTIFY_STATE: ${SPOTIFY_STATE}
      SPOTIFY_SCOPE: ${SPOTIFY_SCOPE}
    command: [ "java", "-jar", "/app/esteira.jar" ]
    env_file:
      - ./.env

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: banco_da_esteira
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
